### ISSUE TITLE
curl error 23

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/http-extractor#25]
```
[2018-07-27 09:05:44] CRITICAL: GuzzleHttp\Exception\RequestException:cURL error 23: Failed writing body (6702 != 16384) (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) {\"errFile\":\"/code/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php\",\"errLine\":186,\"errCode\":200,\"errTrace\":\"#0 /code/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /code/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /code/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /code/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /code/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /code/vendor/guzzlehttp/guzzle/src/RetryMiddleware.php(67): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /code/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\RetryMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /code/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#8 /code/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#9 /code/vendor/guzzlehttp/guzzle/src/Middleware.php(60): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#10 /code/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#11 /code/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#12 /code/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#13 /code/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('get', Object(GuzzleHttp\Psr7\Uri), Array)
#14 /code/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('get', Object(GuzzleHttp\Psr7\Uri), Array)
#15 /code/src/HttpExtractor.php(39): GuzzleHttp\Client->__call('get', Array)
#16 /code/src/HttpExtractorComponent.php(41): Keboola\HttpExtractor\HttpExtractor->extract(Object(GuzzleHttp\Psr7\Uri), '/data/out/files...')
#17 /code/src/run.php(14): Keboola\HttpExtractor\HttpExtractorComponent->run()
#18 {main}\",\"errPrevious\":\"\"} []",
```
viz. https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2018/07/27/11/2018-07-27-11-05-45-5b5ae069b87d5-log

**Comment by odinuv** [comment]
to je spravne application error, ne?

**Comment by ondrejhlavacek** [comment]
jj, to je

**Comment by odinuv** [comment]
takze to muzem zavrit, ne?

**Comment by ondrejhlavacek** [comment]
pokud to vyřeší ten upravenej stack, tak jo

**Comment by odinuv** [comment]
no i kdyby ne, tak s tim ex-http nic nenadela

**Comment by ondrejhlavacek** [comment]
třeba retry?

**Comment by odinuv** [comment]
to je blbost, to bysme takhle mohli pridavat do vsech extractoru retry ze nejde zapsat na disk

**Comment by ondrejhlavacek** [comment]
ok!

**Comment by tomasfejfar** [comment]
> This happens when a piped program (e.g. grep) closes the read pipe before the previous program is finished writing the whole page.
> -- https://stackoverflow.com/a/28879552/112000

**Comment by ondrejhlavacek** [comment]
pro evidenci, stalo se to znova

https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2018/08/04/03/2018-08-04-03-05-41-5b64fbe57e0e3-exception
https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2018/08/04/03/2018-08-04-03-05-41-5b64fbe582934-log

**Comment by tomasfejfar** [comment]
Příčinou může být i málo místa na disku: https://support.plesk.com/hc/en-us/articles/213905925-Unable-to-update-plugins-for-WordPress-installation-cURL-error-23-Failed-writing-body

**Comment by tomasfejfar** [comment]
Taky možnost: https://core.trac.wordpress.org/ticket/38226
