### ISSUE TITLE
Retry CURLE_PARTIAL_FILE (cURL error 18)

### ISSUE THREAD

**Issue by pivnicek** [keboola/http-extractor#26]
`CURLE_PARTIAL_FILE` -- https://curl.haxx.se/libcurl/c/libcurl-errors.html
This should maybe be retried?

full stack trace:
```
CRITICAL: GuzzleHttp\Exception\RequestException:cURL error 18: transfer closed with 93525720 bytes remaining to read (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) {"errFile":"/code/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php","errLine":186,"errCode":200,"errTrace":"#0 /code/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array)\n#1 /code/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#2 /code/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#3 /code/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#4 /code/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)\n#5 /code/vendor/guzzlehttp/guzzle/src/RetryMiddleware.php(67): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)\n#6 /code/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\\RetryMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#7 /code/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#8 /code/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)\n#9 /code/vendor/guzzlehttp/guzzle/src/Middleware.php(60): GuzzleHttp\\RedirectMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#10 /code/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)\n#11 /code/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\\HandlerStack->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#12 /code/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\\Client->transfer(Object(GuzzleHttp\\Psr7\\Request), Array)\n#13 /code/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\\Client->requestAsync('get', Object(GuzzleHttp\\Psr7\\Uri), Array)\n#14 /code/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\\Client->request('get', Object(GuzzleHttp\\Psr7\\Uri), Array)\n#15 /code/src/HttpExtractor.php(39): GuzzleHttp\\Client->__call('get', Array)\n#16 /code/src/HttpExtractorComponent.php(41): Keboola\\HttpExtractor\\HttpExtractor->extract(Object(GuzzleHttp\\Psr7\\Uri), '/data/out/files...')\n#17 /code/src/run.php(14): Keboola\\HttpExtractor\\HttpExtractorComponent->run()\n#18 {main}","errPrevious":""
```

**Comment by pivnicek** [comment]
again today https://keboola.slack.com/archives/C09U3R1J4/p1544447469038200

**Comment by tomasfejfar** [comment]
I'll try to fix this today.

**Comment by odinuv** [comment]
to je divny - Dec 22 08:05:40 se objevilo CRITICAL: GuzzleHttp\Exception\RequestException:cURL error 18: transfer closed with 281739207 bytes remaining to read https://keboola.slack.com/archives/C09U3R1J4/p1545462428003600 a to uz ta nova verze byla nasazena

**Comment by tomasfejfar** [comment]
Tohle ale neznamená, že to nemůže vyhodit AppException. Tohle jen znamená, že to zkusí 3x, než to na tom vyhučí. Je otázka, jestli z toho dělat UserException. Možná jo, nejspíš je to nějaký problém toho zdrojového serveru... že pošle velikost špatně. Třeba to může být nějaký PHP skript, který pošle velikost souboru a content je pak zagzipnutý nebo tak něco...

**Comment by odinuv** [comment]
aha, to jsem si nevsim, loguje to ty retries? curl 18 muze mit asi 1000x ruznejch pricin a jelikoz se tohle zda se objevilo nahodne, tak to vypada na nejaky preruseni spojeni nebo chciplej server, takze je zvlastni, ze by na toten retry nezabral (resp. ze by dostal 3x stejnej a zrovna tenhle error)
